target-version = "py312"

[lint]
select = ["E", "F", "W", "I", "N", "UP", "B", "A", "C4", "T20", "SIM"]
ignore = [
    "E402",
    "F401",
    "E501",
    "B008",
    "B904",
    "UP035",
    "UP042",
    "UP045",
    "UP017",
    "UP011",
    "I001",
    "W291",
    "W292",
    "W293",
    "N806",
    "N812",
    "SIM105",
    "SIM108",
    "B905",
    "T201",
    "UP037",
    "UP041",
    "SIM102",
]

[lint.per-file-ignores]
"__init__.py" = ["F401"]
